export const APP_CATALOGS: Record<string, { name: string; src: string }> = {
  finder: { name: "Finder", src: "/images/finder.webp" },
  safari: { name: "Safari", src: "/images/safari.webp" },
  notes: { name: "Notes", src: "/images/notes.webp" },
  messages: { name: "Messages", src: "/images/messages.webp" },
  calendar: { name: "Calendar", src: "/images/calendar.webp" },
  facetime: { name: "FaceTime", src: "/images/facetime.webp" },
  "app-store": { name: "App Store", src: "/images/app-store.webp" },
  bluetooth: { name: "Bluetooth", src: "/images/bluetooth.webp" },
  calculator: { name: "Calculator", src: "/images/calculator.webp" },
  settings: { name: "Settings", src: "/images/settings.webp" },
  siri: { name: "Siri", src: "/images/siri.webp" },
  terminal: { name: "Terminal", src: "/images/terminal.webp" },
  "voice-memos": { name: "Voice Memos", src: "/images/voice-memos.webp" },
  launchpad: { name: "Launchpad", src: "/images/launchpad.png" },
  bin: { name: "Bin", src: "/images/bin.png" },
  dictionary:{ name: "Dictionary", src: "/images/dictionary.webp" },
  chess:{ name: "Chess", src: "/images/chess.webp" },
  contacts:{ name: "Contacts", src: "/images/contacts.webp" },
  music:{ name: "Music", src: "/images/music.webp" },
};

